### PR TITLE
Just trim whitespace instead of trying to escape it and double-quotes

### PR DESCRIPTION
**Pull request by p-kimberley**
The recent change with #3113 strips quote characters surrounding a term. The workaround is for users to manually escape these (e.g. `\"term value\"`), which is less than ideal - as the quotes are otherwise silently removed.

The original issue #3111 simply called for whitespace to be ignored (i.e. removed). This PR brings behaviour inline with that request, preserving quotes surrounding the term value in the process. Any internal whitespace will be preserved, without the need for escaping.

### CODE REVIEW

**Comment by at055612** [comment]
For reference this is the current stripping behaviour introduced in #3113 (as taken from TestStringUtil)
```
input: 'null'                      , expected output: 'null'
input: ''                          , expected output: ''
input: ' '                         , expected output: ''
input: '      '                    , expected output: ''
input: '   \"   '                  , expected output: '"'
input: '	'                        , expected output: ''
input: 'abc'                       , expected output: 'abc'
input: ' abc'                      , expected output: 'abc'
input: 'abc '                      , expected output: 'abc'
input: ' abc '                     , expected output: 'abc'
input: '    abc    '               , expected output: 'abc'
input: '	abc	'                    , expected output: 'abc'
input: '"abc"'                     , expected output: 'abc'
input: '\"abc\"'                   , expected output: '"abc"'
input: ' "abc" '                   , expected output: 'abc'
input: ' \"abc\" '                 , expected output: '"abc"'
input: ' " abc " '                 , expected output: ' abc '
input: ' \" abc \" '               , expected output: '" abc "'
input: ' " abc  '                  , expected output: '" abc'
input: ' " my name is \"Bob\". " ' , expected output: ' my name is "Bob". '
```

**Comment by at055612** [comment]
Following discussions around lucene/elastic's use of dbl quotes it seems we need to revert #3113 and just do whitespace stripping as per this PR.

However please can you not delete the methods added to StringUtil (or their tests).  Even if they are not used, they may prove useful at some point

**Comment by p-kimberley** [comment]
@at055612 deleted methods have been restored.

**Comment by at055612** [comment]
This PR has been replaced by #3181 which is based on 7.0.

**Pull request closed without merging**
